-- ==========================================
-- 1. TEACHERS TABLE
-- Stores teacher login and profile details.
-- One teacher can teach multiple subjects.
-- ==========================================

CREATE TABLE teachers ( 
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Auto-generated unique ID for every teacher.

    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT,
    CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id)
    -- PRIMARY KEY uniquely identifies each teacher.
); 


-- ==========================================
-- 2. STUDENTS TABLE
-- Stores student details and biometric embeddings.
-- ==========================================

CREATE TABLE students ( 
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    face_embedding JSONB,
    -- JSONB is PostgreSQL's optimized binary JSON type.
    voice_embedding JSONB,
    CONSTRAINT students_pkey PRIMARY KEY (student_id)
); 

-- ==========================================
-- 3. SUBJECTS TABLE
-- Stores subject details.
-- Each subject can be assigned to one teacher.
-- ==========================================
CREATE TABLE subjects ( 
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_code TEXT NOT NULL,
    -- Example: AIML301, DBMS202
    name TEXT DEFAULT 'UNKNOWN',
    section TEXT DEFAULT 'N/A',
    teacher_id BIGINT REFERENCES teachers(teacher_id) 
        ON DELETE SET NULL,
    -- FOREIGN KEY creates relationship:
    -- subjects.teacher_id -> teachers.teacher_id
    --
    -- ON DELETE SET NULL means:
    -- if a teacher is deleted,
    -- the subject will NOT be deleted.
    -- Only teacher_id becomes NULL.

    CONSTRAINT subjects_pkey PRIMARY KEY (subject_id)
); 


-- ==========================================
-- 4. SUBJECT_STUDENT TABLE
-- Junction / bridge table.
--
-- Used because Student <-> Subject is a
-- MANY-TO-MANY relationship.
--
-- One student can have many subjects.
-- One subject can contain many students.
-- ==========================================

CREATE TABLE subject_student ( 

    student_id BIGINT REFERENCES students(student_id) 
        ON DELETE CASCADE,
    -- If student is deleted,
    -- their subject enrollments are also deleted.

    subject_id BIGINT REFERENCES subjects(subject_id) 
        ON DELETE CASCADE,
    -- If subject is deleted,
    -- all student enrollments for that subject are deleted.

    CONSTRAINT subject_student_pkey 
        PRIMARY KEY (student_id, subject_id)
    -- Composite Primary Key.
    --
    -- Prevents duplicate enrollment.
); 


-- ==========================================
-- 5. ATTENDANCE_LOGS TABLE
-- Stores attendance records of students.
--
-- Each row tells:
-- Which student?
-- Which subject?
-- At what time?
-- Present or absent?
-- ==========================================

CREATE TABLE attendance_logs ( 

    id BIGINT GENERATED BY DEFAULT AS IDENTITY 
        PRIMARY KEY,
    -- Unique attendance record ID.

    timestamp TIMESTAMPTZ DEFAULT NOW(),
    -- TIMESTAMPTZ = Timestamp With Time Zone.
    -- NOW() automatically stores current date and time.

    subject_id BIGINT REFERENCES subjects(subject_id) 
        ON DELETE CASCADE,
    -- Attendance belongs to a subject.
    --
    -- If subject is deleted,
    -- its attendance records are also deleted.

    student_id BIGINT REFERENCES students(student_id) 
        ON DELETE CASCADE,
    -- Attendance belongs to a student.
    --
    -- If student is deleted,
    -- their attendance records are also deleted.

    is_present BOOLEAN DEFAULT TRUE
    -- TRUE  = Present
    -- FALSE = Absent
    --
    -- Default is TRUE because normally
    -- a recognition event means student was detected.
);


