CREATE TABLE teachers ( 
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT,
    CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id)
); 

-- SESSION MANAGEMENT: Persistent teacher sessions. Raw tokens are never saved;
-- token_hash contains only the SHA-256 digest used for server-side validation.
CREATE TABLE user_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    token_hash TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX user_sessions_teacher_id_idx ON user_sessions(teacher_id);
CREATE INDEX user_sessions_expires_at_idx ON user_sessions(expires_at);

CREATE TABLE students ( 
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    face_embedding JSONB,
    face_embeddings JSONB NOT NULL DEFAULT '[]'::jsonb,
    voice_embedding JSONB,
    CONSTRAINT students_pkey PRIMARY KEY (student_id)
); 

CREATE TABLE subjects ( 
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_code TEXT NOT NULL,
    name TEXT DEFAULT 'UNKNOWN',
    section TEXT DEFAULT 'N/A',
    teacher_id BIGINT REFERENCES teachers(teacher_id) 
        ON DELETE SET NULL,
    CONSTRAINT subjects_pkey PRIMARY KEY (subject_id)
); 


CREATE TABLE subject_student ( 
    student_id BIGINT REFERENCES students(student_id) 
        ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(subject_id) 
        ON DELETE CASCADE,
    CONSTRAINT subject_student_pkey 
        PRIMARY KEY (student_id, subject_id)
); 


-- FEATURE 2: Every lecture is a first-class session instead of a timestamp group.
CREATE TABLE attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
    teacher_id BIGINT NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Attendance session',
    attendance_method TEXT NOT NULL DEFAULT 'face',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'draft'
);

CREATE TABLE attendance_logs ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES attendance_sessions(session_id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE,
    -- FEATURE 2: ai_is_present preserves the model decision; is_present is final.
    ai_is_present BOOLEAN,
    is_present BOOLEAN DEFAULT TRUE
);

-- FEATURE 2: Keep every manual change instead of silently overwriting history.
CREATE TABLE attendance_corrections (
    correction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_log_id BIGINT NOT NULL REFERENCES attendance_logs(id) ON DELETE CASCADE,
    corrected_by BIGINT NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    previous_status BOOLEAN NOT NULL,
    new_status BOOLEAN NOT NULL,
    reason TEXT NOT NULL,
    corrected_at TIMESTAMPTZ DEFAULT NOW()
);
